version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
      network: host
    volumes:
      - .:/usr/src/pr
      - /home/DreD/work/pr/node_modules
   
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/run/postgresql/data
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/run/postgresql/data
networks:
  webnet:
    driver: bridge
volumes:
  pgdata: